// Copyright (C) 2013  Paul Miller. This file is part of TX Modular system distributed under the terms of the GNU General Public License (see file LICENSE).

TXV_Draw2DDelayCurves : TXV_Module {
	classvar <defaultName = "TXV 2D Delay Curves";
	classvar <>arrInstances;

	// add text array to ..."maxWidthHeightRule":
	// , ["Use Screen Width & Height", "Square - Use Max of Screen Width & Height", "Square - Use Min of Screen Width & Height", "Square - Use Screen Width", "Square - Use Screen Height", "Use Custom Size", ]

	// add text array to ..."curveType/fixedValue":
	// , ["Automatic curve", "Straight line", "Bezier curve using control point 1", "Bezier curve using control point 1, smoothed", "Bezier curve using control points 1 & 2"]

	// add text array to ..."spreadType/fixedValue":  [from ofxTweenLite]
	// , ["Back In", "Back Out", "Back In & Out", "Bounce In", "Bounce Out", "Bounce In & Out", "Circular In", "Circular Out", "Circular In & Out", "Cubic In", "Cubic Out", "Cubic In & Out", "Elastic In", "Elastic Out", "Elastic In & Out", "Exponential In", "Exponential Out", "Exponential In & Out", "Linear In (default)", "Linear Out", "Linear In & Out", "Quadratic In", "Quadratic Out", "Quadratic In & Out", "Quartic In", "Quartic Out", "Quartic In & Out", "Quintic In", "Quintic Out", "Quintic In & Out", "Sine In", "Sine Out", "Sine In & Out"]

	// add text array to ..."windingMode/fixedValue":
	// , ["Odd - allows holes (default)", "Non-Zero - outline, no holes,  autoClose", ]

	getTXVParameters{ ^[
		/* ---------- TXV Settable Parameter list for: TXDraw2DDelayCurves_1 ---------- */
		/* GROUP:     [groupType, address, parameters] */
		/* PARAMETER: [parameterType, address, val, ?min, ?max] */
		[ "modParameterGroupBool", "/TXDraw2DDelayCurves_1/drawActive", [
			["bool_int", "/TXDraw2DDelayCurves_1/drawActive/fixedValue", 1],
			["bool_int", "/TXDraw2DDelayCurves_1/drawActive/fixedModMix", 0],
			["bool_int", "/TXDraw2DDelayCurves_1/drawActive/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/drawActive/extModValue", 0, 0, 1],
		]],
		["int", "/TXDraw2DDelayCurves_1/maxWidthHeightRule", 0, 0, 5, ["Use Screen Width & Height", "Square - Use Max of Screen Width & Height", "Square - Use Min of Screen Width & Height", "Square - Use Screen Width", "Square - Use Screen Height", "Use Custom Size", ]],
		["int", "/TXDraw2DDelayCurves_1/customMaxWidth", 1024, 1, 4096],
		["int", "/TXDraw2DDelayCurves_1/customMaxHeight", 768, 1, 4096],
		[ "modParameterGroupInt", "/TXDraw2DDelayCurves_1/delayFrames", [
			["int", "/TXDraw2DDelayCurves_1/delayFrames/fixedValue", 60, 0, 1000],
			["float", "/TXDraw2DDelayCurves_1/delayFrames/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/delayFrames/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/delayFrames/extModValue", 0, 0, 1],
			["int", "/TXDraw2DDelayCurves_1/delayFrames/softMin", 0, 0, 1000],
			["int", "/TXDraw2DDelayCurves_1/delayFrames/softMax", 1000, 0, 1000],
		]],
		[ "modParameterGroupInt", "/TXDraw2DDelayCurves_1/curveType", [
			["int", "/TXDraw2DDelayCurves_1/curveType/fixedValue", 0, 0, 4, ["Automatic curve", "Straight line", "Bezier curve using control point 1", "Bezier curve using control point 1, smoothed", "Bezier curve using control points 1 & 2"]],
			["float", "/TXDraw2DDelayCurves_1/curveType/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/curveType/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/curveType/extModValue", 0, 0, 1],
			["int", "/TXDraw2DDelayCurves_1/curveType/softMin", 0, 0, 4],
			["int", "/TXDraw2DDelayCurves_1/curveType/softMax", 4, 0, 4],
		]],
		[ "modParameterGroupInt", "/TXDraw2DDelayCurves_1/numCurves", [
			["int", "/TXDraw2DDelayCurves_1/numCurves/fixedValue", 4, 1, 100],
			["float", "/TXDraw2DDelayCurves_1/numCurves/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/numCurves/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/numCurves/extModValue", 0, 0, 1],
			["int", "/TXDraw2DDelayCurves_1/numCurves/softMin", 1, 0, 1000],
			["int", "/TXDraw2DDelayCurves_1/numCurves/softMax", 100, 0, 1000],
		]],
		[ "modParameterGroupInt", "/TXDraw2DDelayCurves_1/numPoints", [
			["int", "/TXDraw2DDelayCurves_1/numPoints/fixedValue", 2, 2, 8],
			["float", "/TXDraw2DDelayCurves_1/numPoints/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/numPoints/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/numPoints/extModValue", 0, 0, 1],
			["int", "/TXDraw2DDelayCurves_1/numPoints/softMin", 2, 2, 8],
			["int", "/TXDraw2DDelayCurves_1/numPoints/softMax", 8, 2, 8],
		]],
		[ "modParameterGroupInt", "/TXDraw2DDelayCurves_1/lineWidth", [
			["int", "/TXDraw2DDelayCurves_1/lineWidth/fixedValue", 4, 0, 10],
			["float", "/TXDraw2DDelayCurves_1/lineWidth/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/lineWidth/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/lineWidth/extModValue", 0, 0, 1],
			["int", "/TXDraw2DDelayCurves_1/lineWidth/softMin", 0, 0, 10],
			["int", "/TXDraw2DDelayCurves_1/lineWidth/softMax", 10, 0, 10],
		]],
		[ "modParameterGroupInt", "/TXDraw2DDelayCurves_1/spreadType", [
			["int", "/TXDraw2DDelayCurves_1/spreadType/fixedValue", 18, 0, 32 , ["Back In", "Back Out", "Back In & Out", "Bounce In", "Bounce Out", "Bounce In & Out", "Circular In", "Circular Out", "Circular In & Out", "Cubic In", "Cubic Out", "Cubic In & Out", "Elastic In", "Elastic Out", "Elastic In & Out", "Exponential In", "Exponential Out", "Exponential In & Out", "Linear In (default)", "Linear Out", "Linear In & Out", "Quadratic In", "Quadratic Out", "Quadratic In & Out", "Quartic In", "Quartic Out", "Quartic In & Out", "Quintic In", "Quintic Out", "Quintic In & Out", "Sine In", "Sine Out", "Sine In & Out"]],
			["float", "/TXDraw2DDelayCurves_1/spreadType/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/spreadType/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/spreadType/extModValue", 0, 0, 1],
			["int", "/TXDraw2DDelayCurves_1/spreadType/softMin", 0, 0, 32],
			["int", "/TXDraw2DDelayCurves_1/spreadType/softMax", 32, 0, 32],
		]],
		[ "modParameterGroupInt", "/TXDraw2DDelayCurves_1/spreadType2", [
			["int", "/TXDraw2DDelayCurves_1/spreadType2/fixedValue", 18, 0, 32 , ["Back In", "Back Out", "Back In & Out", "Bounce In", "Bounce Out", "Bounce In & Out", "Circular In", "Circular Out", "Circular In & Out", "Cubic In", "Cubic Out", "Cubic In & Out", "Elastic In", "Elastic Out", "Elastic In & Out", "Exponential In", "Exponential Out", "Exponential In & Out", "Linear In (default)", "Linear Out", "Linear In & Out", "Quadratic In", "Quadratic Out", "Quadratic In & Out", "Quartic In", "Quartic Out", "Quartic In & Out", "Quintic In", "Quintic Out", "Quintic In & Out", "Sine In", "Sine Out", "Sine In & Out"]],
			["float", "/TXDraw2DDelayCurves_1/spreadType2/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/spreadType2/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/spreadType2/extModValue", 0, 0, 1],
			["int", "/TXDraw2DDelayCurves_1/spreadType2/softMin", 0, 0, 32],
			["int", "/TXDraw2DDelayCurves_1/spreadType2/softMax", 32, 0, 32],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/spreadTypeMorph", [
			["float", "/TXDraw2DDelayCurves_1/spreadTypeMorph/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/spreadTypeMorph/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/spreadTypeMorph/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/spreadTypeMorph/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/spreadTypeMorph/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/spreadTypeMorph/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupBool", "/TXDraw2DDelayCurves_1/autoClose", [
			["bool_int", "/TXDraw2DDelayCurves_1/autoClose/fixedValue", 0],
			["bool_int", "/TXDraw2DDelayCurves_1/autoClose/fixedModMix", 0],
			["bool_int", "/TXDraw2DDelayCurves_1/autoClose/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/autoClose/extModValue", 0, 0, 1],
		]],
		[ "modParameterGroupBool", "/TXDraw2DDelayCurves_1/fillShape", [
			["bool_int", "/TXDraw2DDelayCurves_1/fillShape/fixedValue", 0],
			["bool_int", "/TXDraw2DDelayCurves_1/fillShape/fixedModMix", 0],
			["bool_int", "/TXDraw2DDelayCurves_1/fillShape/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/fillShape/extModValue", 0, 0, 1],
		]],
		[ "modParameterGroupInt", "/TXDraw2DDelayCurves_1/windingMode", [
			["int", "/TXDraw2DDelayCurves_1/windingMode/fixedValue", 0, 0, 1, ["Odd - allows holes (default)", "Non-Zero - outline, no holes,  autoClose", ]],
			["float", "/TXDraw2DDelayCurves_1/windingMode/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/windingMode/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/windingMode/extModValue", 0, 0, 1],
			["int", "/TXDraw2DDelayCurves_1/windingMode/softMin", 0, 0, 1],
			["int", "/TXDraw2DDelayCurves_1/windingMode/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupInt", "/TXDraw2DDelayCurves_1/curveResolution", [
			["int", "/TXDraw2DDelayCurves_1/curveResolution/fixedValue", 64, 2, 128],
			["float", "/TXDraw2DDelayCurves_1/curveResolution/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/curveResolution/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/curveResolution/extModValue", 0, 0, 1],
			["int", "/TXDraw2DDelayCurves_1/curveResolution/softMin", 2, 2, 1024],
			["int", "/TXDraw2DDelayCurves_1/curveResolution/softMax", 128, 2, 1024],
		]],
		[ "modParameterGroupBool", "/TXDraw2DDelayCurves_1/reverseCurveOrder", [
			["bool_int", "/TXDraw2DDelayCurves_1/reverseCurveOrder/fixedValue", 0],
			["bool_int", "/TXDraw2DDelayCurves_1/reverseCurveOrder/fixedModMix", 0],
			["bool_int", "/TXDraw2DDelayCurves_1/reverseCurveOrder/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/reverseCurveOrder/extModValue", 0, 0, 1],
		]],
		[ "modParameterGroupBool", "/TXDraw2DDelayCurves_1/drawControlPoints", [
			["bool_int", "/TXDraw2DDelayCurves_1/drawControlPoints/fixedValue", 0],
			["bool_int", "/TXDraw2DDelayCurves_1/drawControlPoints/fixedModMix", 0],
			["bool_int", "/TXDraw2DDelayCurves_1/drawControlPoints/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/drawControlPoints/extModValue", 0, 0, 1],
		]],
		["bool_int", "/TXDraw2DDelayCurves_1/swapColorWithFillColor", 0],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/colorHue", [
			["float", "/TXDraw2DDelayCurves_1/colorHue/fixedValue", 0.5, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHue/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/colorHue/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/colorHue/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHue/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHue/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/colorHueRotate", [
			["float", "/TXDraw2DDelayCurves_1/colorHueRotate/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHueRotate/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/colorHueRotate/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/colorHueRotate/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHueRotate/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHueRotate/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/colorSaturation", [
			["float", "/TXDraw2DDelayCurves_1/colorSaturation/fixedValue", 0.6, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorSaturation/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/colorSaturation/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/colorSaturation/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorSaturation/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorSaturation/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/colorBrightness", [
			["float", "/TXDraw2DDelayCurves_1/colorBrightness/fixedValue", 0.5, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorBrightness/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/colorBrightness/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/colorBrightness/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorBrightness/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorBrightness/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/colorAlpha", [
			["float", "/TXDraw2DDelayCurves_1/colorAlpha/fixedValue", 1, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorAlpha/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/colorAlpha/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/colorAlpha/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorAlpha/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorAlpha/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/colorHueEnd", [
			["float", "/TXDraw2DDelayCurves_1/colorHueEnd/fixedValue", 0.5, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHueEnd/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/colorHueEnd/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/colorHueEnd/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHueEnd/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHueEnd/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/colorHueRotateEnd", [
			["float", "/TXDraw2DDelayCurves_1/colorHueRotateEnd/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHueRotateEnd/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/colorHueRotateEnd/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/colorHueRotateEnd/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHueRotateEnd/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorHueRotateEnd/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/colorSaturationEnd", [
			["float", "/TXDraw2DDelayCurves_1/colorSaturationEnd/fixedValue", 0.6, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorSaturationEnd/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/colorSaturationEnd/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/colorSaturationEnd/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorSaturationEnd/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorSaturationEnd/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/colorBrightnessEnd", [
			["float", "/TXDraw2DDelayCurves_1/colorBrightnessEnd/fixedValue", 0.5, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorBrightnessEnd/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/colorBrightnessEnd/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/colorBrightnessEnd/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorBrightnessEnd/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorBrightnessEnd/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/colorAlphaEnd", [
			["float", "/TXDraw2DDelayCurves_1/colorAlphaEnd/fixedValue", 1, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorAlphaEnd/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/colorAlphaEnd/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/colorAlphaEnd/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorAlphaEnd/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/colorAlphaEnd/softMax", 1, 0, 1],
		]],
		["bool_int", "/TXDraw2DDelayCurves_1/useColorHueForEndColor", 0],
		["bool_int", "/TXDraw2DDelayCurves_1/useColorSaturationForEndColor", 0],
		["bool_int", "/TXDraw2DDelayCurves_1/useColorBrightnessForEndColor", 0],
		["bool_int", "/TXDraw2DDelayCurves_1/useColorAlphaForEndColor", 0],
		["bool_int", "/TXDraw2DDelayCurves_1/colorHSBAsRGB", 0],
		["bool_int", "/TXDraw2DDelayCurves_1/useColorForFillColor", 1],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/fillColorHue", [
			["float", "/TXDraw2DDelayCurves_1/fillColorHue/fixedValue", 0.5, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHue/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/fillColorHue/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/fillColorHue/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHue/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHue/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/fillColorHueRotate", [
			["float", "/TXDraw2DDelayCurves_1/fillColorHueRotate/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueRotate/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/fillColorHueRotate/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueRotate/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueRotate/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueRotate/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/fillColorSaturation", [
			["float", "/TXDraw2DDelayCurves_1/fillColorSaturation/fixedValue", 0.6, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorSaturation/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/fillColorSaturation/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/fillColorSaturation/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorSaturation/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorSaturation/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/fillColorBrightness", [
			["float", "/TXDraw2DDelayCurves_1/fillColorBrightness/fixedValue", 0.5, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorBrightness/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/fillColorBrightness/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/fillColorBrightness/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorBrightness/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorBrightness/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/fillColorAlpha", [
			["float", "/TXDraw2DDelayCurves_1/fillColorAlpha/fixedValue", 1, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorAlpha/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/fillColorAlpha/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/fillColorAlpha/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorAlpha/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorAlpha/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/fillColorHueEnd", [
			["float", "/TXDraw2DDelayCurves_1/fillColorHueEnd/fixedValue", 0.5, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueEnd/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/fillColorHueEnd/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueEnd/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueEnd/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueEnd/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/fillColorHueRotateEnd", [
			["float", "/TXDraw2DDelayCurves_1/fillColorHueRotateEnd/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueRotateEnd/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/fillColorHueRotateEnd/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueRotateEnd/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueRotateEnd/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorHueRotateEnd/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/fillColorSaturationEnd", [
			["float", "/TXDraw2DDelayCurves_1/fillColorSaturationEnd/fixedValue", 0.6, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorSaturationEnd/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/fillColorSaturationEnd/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/fillColorSaturationEnd/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorSaturationEnd/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorSaturationEnd/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/fillColorBrightnessEnd", [
			["float", "/TXDraw2DDelayCurves_1/fillColorBrightnessEnd/fixedValue", 0.5, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorBrightnessEnd/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/fillColorBrightnessEnd/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/fillColorBrightnessEnd/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorBrightnessEnd/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorBrightnessEnd/softMax", 1, 0, 1],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/fillColorAlphaEnd", [
			["float", "/TXDraw2DDelayCurves_1/fillColorAlphaEnd/fixedValue", 1, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorAlphaEnd/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/fillColorAlphaEnd/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/fillColorAlphaEnd/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorAlphaEnd/softMin", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/fillColorAlphaEnd/softMax", 1, 0, 1],
		]],
		["bool_int", "/TXDraw2DDelayCurves_1/useFillColorHueForEndColor", 0],
		["bool_int", "/TXDraw2DDelayCurves_1/useFillColorSaturationForEndColor", 0],
		["bool_int", "/TXDraw2DDelayCurves_1/useFillColorBrightnessForEndColor", 0],
		["bool_int", "/TXDraw2DDelayCurves_1/useFillColorAlphaForEndColor", 0],
		["bool_int", "/TXDraw2DDelayCurves_1/fillColorHSBAsRGB", 0],
		["bool_int", "/TXDraw2DDelayCurves_1/usePoint1ForAutoCurveStart", 0],
		["bool_int", "/TXDraw2DDelayCurves_1/useLastPointForAutoCurveEnd", 0],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point1_drawX", [
			["float", "/TXDraw2DDelayCurves_1/point1_drawX/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point1_drawX/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point1_drawX/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point1_drawX/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point1_drawX/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point1_drawX/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point1_drawY", [
			["float", "/TXDraw2DDelayCurves_1/point1_drawY/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point1_drawY/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point1_drawY/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point1_drawY/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point1_drawY/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point1_drawY/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point2_control1X", [
			["float", "/TXDraw2DDelayCurves_1/point2_control1X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_control1X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point2_control1X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point2_control1X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_control1X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point2_control1X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point2_control1Y", [
			["float", "/TXDraw2DDelayCurves_1/point2_control1Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_control1Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point2_control1Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point2_control1Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_control1Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point2_control1Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point2_control2X", [
			["float", "/TXDraw2DDelayCurves_1/point2_control2X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_control2X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point2_control2X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point2_control2X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_control2X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point2_control2X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point2_control2Y", [
			["float", "/TXDraw2DDelayCurves_1/point2_control2Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_control2Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point2_control2Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point2_control2Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_control2Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point2_control2Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point2_drawX", [
			["float", "/TXDraw2DDelayCurves_1/point2_drawX/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_drawX/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point2_drawX/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point2_drawX/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_drawX/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point2_drawX/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point2_drawY", [
			["float", "/TXDraw2DDelayCurves_1/point2_drawY/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_drawY/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point2_drawY/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point2_drawY/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point2_drawY/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point2_drawY/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point3_control1X", [
			["float", "/TXDraw2DDelayCurves_1/point3_control1X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_control1X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point3_control1X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point3_control1X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_control1X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point3_control1X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point3_control1Y", [
			["float", "/TXDraw2DDelayCurves_1/point3_control1Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_control1Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point3_control1Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point3_control1Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_control1Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point3_control1Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point3_control2X", [
			["float", "/TXDraw2DDelayCurves_1/point3_control2X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_control2X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point3_control2X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point3_control2X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_control2X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point3_control2X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point3_control2Y", [
			["float", "/TXDraw2DDelayCurves_1/point3_control2Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_control2Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point3_control2Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point3_control2Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_control2Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point3_control2Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point3_drawX", [
			["float", "/TXDraw2DDelayCurves_1/point3_drawX/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_drawX/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point3_drawX/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point3_drawX/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_drawX/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point3_drawX/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point3_drawY", [
			["float", "/TXDraw2DDelayCurves_1/point3_drawY/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_drawY/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point3_drawY/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point3_drawY/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point3_drawY/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point3_drawY/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point4_control1X", [
			["float", "/TXDraw2DDelayCurves_1/point4_control1X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_control1X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point4_control1X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point4_control1X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_control1X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point4_control1X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point4_control1Y", [
			["float", "/TXDraw2DDelayCurves_1/point4_control1Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_control1Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point4_control1Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point4_control1Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_control1Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point4_control1Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point4_control2X", [
			["float", "/TXDraw2DDelayCurves_1/point4_control2X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_control2X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point4_control2X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point4_control2X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_control2X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point4_control2X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point4_control2Y", [
			["float", "/TXDraw2DDelayCurves_1/point4_control2Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_control2Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point4_control2Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point4_control2Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_control2Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point4_control2Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point4_drawX", [
			["float", "/TXDraw2DDelayCurves_1/point4_drawX/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_drawX/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point4_drawX/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point4_drawX/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_drawX/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point4_drawX/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point4_drawY", [
			["float", "/TXDraw2DDelayCurves_1/point4_drawY/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_drawY/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point4_drawY/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point4_drawY/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point4_drawY/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point4_drawY/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point5_control1X", [
			["float", "/TXDraw2DDelayCurves_1/point5_control1X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_control1X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point5_control1X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point5_control1X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_control1X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point5_control1X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point5_control1Y", [
			["float", "/TXDraw2DDelayCurves_1/point5_control1Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_control1Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point5_control1Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point5_control1Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_control1Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point5_control1Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point5_control2X", [
			["float", "/TXDraw2DDelayCurves_1/point5_control2X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_control2X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point5_control2X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point5_control2X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_control2X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point5_control2X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point5_control2Y", [
			["float", "/TXDraw2DDelayCurves_1/point5_control2Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_control2Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point5_control2Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point5_control2Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_control2Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point5_control2Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point5_drawX", [
			["float", "/TXDraw2DDelayCurves_1/point5_drawX/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_drawX/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point5_drawX/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point5_drawX/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_drawX/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point5_drawX/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point5_drawY", [
			["float", "/TXDraw2DDelayCurves_1/point5_drawY/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_drawY/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point5_drawY/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point5_drawY/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point5_drawY/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point5_drawY/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point6_control1X", [
			["float", "/TXDraw2DDelayCurves_1/point6_control1X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_control1X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point6_control1X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point6_control1X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_control1X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point6_control1X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point6_control1Y", [
			["float", "/TXDraw2DDelayCurves_1/point6_control1Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_control1Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point6_control1Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point6_control1Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_control1Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point6_control1Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point6_control2X", [
			["float", "/TXDraw2DDelayCurves_1/point6_control2X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_control2X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point6_control2X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point6_control2X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_control2X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point6_control2X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point6_control2Y", [
			["float", "/TXDraw2DDelayCurves_1/point6_control2Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_control2Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point6_control2Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point6_control2Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_control2Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point6_control2Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point6_drawX", [
			["float", "/TXDraw2DDelayCurves_1/point6_drawX/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_drawX/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point6_drawX/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point6_drawX/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_drawX/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point6_drawX/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point6_drawY", [
			["float", "/TXDraw2DDelayCurves_1/point6_drawY/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_drawY/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point6_drawY/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point6_drawY/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point6_drawY/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point6_drawY/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point7_control1X", [
			["float", "/TXDraw2DDelayCurves_1/point7_control1X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_control1X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point7_control1X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point7_control1X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_control1X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point7_control1X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point7_control1Y", [
			["float", "/TXDraw2DDelayCurves_1/point7_control1Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_control1Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point7_control1Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point7_control1Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_control1Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point7_control1Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point7_control2X", [
			["float", "/TXDraw2DDelayCurves_1/point7_control2X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_control2X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point7_control2X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point7_control2X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_control2X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point7_control2X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point7_control2Y", [
			["float", "/TXDraw2DDelayCurves_1/point7_control2Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_control2Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point7_control2Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point7_control2Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_control2Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point7_control2Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point7_drawX", [
			["float", "/TXDraw2DDelayCurves_1/point7_drawX/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_drawX/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point7_drawX/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point7_drawX/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_drawX/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point7_drawX/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point7_drawY", [
			["float", "/TXDraw2DDelayCurves_1/point7_drawY/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_drawY/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point7_drawY/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point7_drawY/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point7_drawY/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point7_drawY/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point8_control1X", [
			["float", "/TXDraw2DDelayCurves_1/point8_control1X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_control1X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point8_control1X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point8_control1X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_control1X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point8_control1X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point8_control1Y", [
			["float", "/TXDraw2DDelayCurves_1/point8_control1Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_control1Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point8_control1Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point8_control1Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_control1Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point8_control1Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point8_control2X", [
			["float", "/TXDraw2DDelayCurves_1/point8_control2X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_control2X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point8_control2X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point8_control2X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_control2X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point8_control2X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point8_control2Y", [
			["float", "/TXDraw2DDelayCurves_1/point8_control2Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_control2Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point8_control2Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point8_control2Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_control2Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point8_control2Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point8_drawX", [
			["float", "/TXDraw2DDelayCurves_1/point8_drawX/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_drawX/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point8_drawX/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point8_drawX/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_drawX/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point8_drawX/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/point8_drawY", [
			["float", "/TXDraw2DDelayCurves_1/point8_drawY/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_drawY/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/point8_drawY/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/point8_drawY/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/point8_drawY/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/point8_drawY/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/autoCurveStart_control1X", [
			["float", "/TXDraw2DDelayCurves_1/autoCurveStart_control1X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/autoCurveStart_control1X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/autoCurveStart_control1X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/autoCurveStart_control1X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/autoCurveStart_control1X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/autoCurveStart_control1X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/autoCurveStart_control1Y", [
			["float", "/TXDraw2DDelayCurves_1/autoCurveStart_control1Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/autoCurveStart_control1Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/autoCurveStart_control1Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/autoCurveStart_control1Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/autoCurveStart_control1Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/autoCurveStart_control1Y/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1X", [
			["float", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1X/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1X/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1X/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1X/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1X/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1X/softMax", 1, -10, 11],
		]],
		[ "modParameterGroupFloat", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1Y", [
			["float", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1Y/fixedValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1Y/fixedModMix", 0, 0, 1],
			["bool_int", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1Y/useExtMod", 0],
			["float", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1Y/extModValue", 0, 0, 1],
			["float", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1Y/softMin", 0, -10, 11],
			["float", "/TXDraw2DDelayCurves_1/autoCurveEnd_control1Y/softMax", 1, -10, 11],
		]],
	];}

	getTXVOutputs{ ^[
		/* ---------- TXV Outputs list for: TXDraw2DDelayCurves_1 ---------- */
		// empty
	];}

	getTXVParameterSectionSpecs {
		^[
			// format: ["Example Name", nameValidityFunction],
			["Spread", {arg parameterName; parameterName.containsi("Spread");}],
			["Points$AutoCurve Start", {arg parameterName; parameterName.containsi("AutoCurveStart");}],
			["Points$Point 1", {arg parameterName; parameterName.containsi("point1");}],
			["Points$Point 2", {arg parameterName; parameterName.containsi("point2");}],
			["Points$Point 3", {arg parameterName; parameterName.containsi("point3");}],
			["Points$Point 4", {arg parameterName; parameterName.containsi("point4");}],
			["Points$Point 5", {arg parameterName; parameterName.containsi("point5");}],
			["Points$Point 6", {arg parameterName; parameterName.containsi("point6");}],
			["Points$Point 7", {arg parameterName; parameterName.containsi("point7");}],
			["Points$Point 8", {arg parameterName; parameterName.containsi("point8");}],
			["Points$AutoCurve End", {arg parameterName; parameterName.containsi("AutoCurveEnd");}],
			["Color", {arg parameterName;
				parameterName.containsi("swap")
				|| (parameterName.containsi("Color") && (parameterName.containsi("fillColor") == false))}],
			["Fill Color", {arg parameterName;
				parameterName.containsi("fillColor");}],
			["Draw", {arg parameterName;
				var drawParameterNames = ["drawActive", "maxWidthHeightRule", "customMaxWidth", "customMaxHeight", "customMaxDepth", "useSamplePosForDrawPos", "useSampleSizeForDrawSize", "constrainToEdges", "alphaThreshold", "alpha", "drawAlpha", "drawPosX", "drawPosY", "drawPosZ", "positionX", "positionY", "positionZ", "drawWidth", "drawHeight", "anchorX", "anchorY", "rotate", "rotateX", "rotateY", "rotateZ", "rotateMultiply", "scaleX", "scaleY", "scaleZ", "useScaleXForScaleY", "useScaleXForScaleZ" ];
				// return validity bool
				drawParameterNames.indexOfEqual(parameterName).notNil;
			}],
			];
		}

getDefaultParamSectionName {  // override
	^"Global";
}

}

